#
#  Do not edit this file.  This file is generated from 
#  package.bld.  Any modifications to this file will be 
#  overwritten whenever makefiles are re-generated.
#
#  target compatibility key = ti.targets.arm.elf.M3{1,0,18.1,1
#
hello.xem3: package/cfg/hello.xem3.mak

clean::
	-$(RM) package/cfg/hello.xem3.mak
